### ISSUE TITLE
Installation and setup

### ISSUE THREAD

**Issue by dinosaw** [CBenni/logviewer#13]
I know you don't advise others to set this up, but any help you could provide would be appreciated.

My first question is, what version of Node do you recommend for this? I've tried 6.x and 8.x and both seem to give me problems.

Right now I've gotten further by using 6.x, however it still stops when I attempt to run index.js:

```
$ node index.js 
error: uncaughtException: Unexpected token ; date=Thu Oct 25 2018 18:31:13 GMT-0400 (EDT), pid=31062, uid=0, gid=0
/root/apps/logviewer/bot.js:343
    let channelObj = {name: data[PARAM].slice(1), id: data[TAGS]["room-id"];
                                                                           ^
SyntaxError: Unexpected token ;
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/apps/logviewer/index.js:176:13)
    at Module._compile (module.js:556:32)
```

I have all the settings.json filled out (excluding Discord configurations).

Any idea what I could be doing wrong?

**Comment by CBenni** [comment]
Some of the newer commits on master are WIPs and are not working, use the hotfix branch instead if you want to develop on the currently active branch.

As for node version, I think it runs on 8.x

**Comment by DarkRTA** [comment]
Even with the hotfix branch, I've had to make some changes to the code in order to get it to work. I'll commit them to a repo at some point

**Comment by dinosaw** [comment]
@TheEssenceOfDarkness Thank ya. I went back and tried using Node 8.x on the hotfix branch and still wasn't working. Just curious what Node version are you using?

**Comment by DarkRTA** [comment]
12.x. It doesn't matter as you will have to modify the code some anyway. When I am done I'll edit this comment with the link to my repo with the changes.

As a side note, do you plan on using this to contribute to the repo, or to have a privately hosted instance?

Edit: I do not plan on submitting a PR with the changes. It would probably break a lot of stuff.

**Comment by dinosaw** [comment]
Unfortunately I'm not a developer so I can't quite contribute. I was wanting to utilize it for a couple different streamers I'm a moderator for.

**Comment by CBenni** [comment]
The hotfix branch is the one that is being used by the server that runs the logviewer right now, not sure what issues you are encountering, can you elaborate on that?
Keep in mind that this project is EOL anyways, it doesnt even support name changes yet.
Logviewer v4 is on hiatus for now as well, until we know exactly what twitchs new logging system looks like.

**Comment by DarkRTA** [comment]
From what I have gathered, most if not all of the issues were caused by outdated dependencies in issue with the html side of things, and settings.default.json not having the config settings for database sharding. (worked around the sharding issue by using an older version of the MySQL adapter)
